programs: 1
    shaders: 2
        shaders/vsh.glsl GL_VERTEX_SHADER
        shaders/fsh.glsl GL_FRAGMENT_SHADER
    variables: 1 0
        u_mvp GL_FLOAT_MAT4 0
    textures: 1
        u_surfaceMap GL_TEXTURE_2D_ARRAY 1
        2 2048 2048
            ../textures/seaTexture.jpg
            ../textures/sandTexture.jpg
        4
            GL_TEXTURE_MAG_FILTER GL_LINEAR
            GL_TEXTURE_MIN_FILTER GL_LINEAR_MIPMAP_LINEAR
            GL_TEXTURE_WRAP_S GL_MIRRORED_REPEAT
            GL_TEXTURE_WRAP_T GL_MIRRORED_REPEAT
    models: 1
        0
    
    END
        
models: 1
    6 heightmap ../heightmaps/australia.jpg 0.1
    3
        3 GL_FLOAT 0 coordinates: predefined
        2 GL_FLOAT 0 texCoordinates: same
        1 GL_INT 0 texLayer: stub
